### ISSUE TITLE
Expelliarmus article

### ISSUE THREAD

**Issue by fabrizio-ottati** [open-neuromorphic/open-neuromorphic.github.io#12]
Write article on Expelliarmus with benchmarks and so on once @stevenabreu7 has run those on his Metavision machine.

**Comment by biphasic** [comment]
first version available here (set to draft=true) https://github.com/open-neuromorphic/open-neuromorphic.github.io/tree/main/content/post/file-reading-benchmarking

**Comment by fabrizio-ottati** [comment]
![image](https://user-images.githubusercontent.com/45739782/212163112-ba847f8d-27d5-406f-8eed-10993f84fdd6.png)

MAY I SAY THAT EXPELLIARMUS IS REALLY COOL?
