### ISSUE TITLE
Review and improve info about Akida by Brainchip

### ISSUE THREAD

**Issue by biphasic** [open-neuromorphic/open-neuromorphic.github.io#143]
## The website
The code for the live version of open-neuromorphic.org is hosted on the `main` branch at [our GitHub repository](https://github.com/open-neuromorphic/open-neuromorphic.github.io). The site contains educational content on neuromorphic software libraries and hardware. 

## What to improve
The current entry for [Akida](https://open-neuromorphic.org/neuromorphic-computing/hardware/akida-brainchip/) is located [here](https://github.com/open-neuromorphic/open-neuromorphic.github.io/tree/main/content/english/neuromorphic-computing/hardware/akida-brainchip) and would benefit from more detailed info. 

Following info should be checked or added in the header:
- [ ] **release_date**. When was the chip released? That means made available for customers to buy/access for industry chips, or the first results published for research chips. 
- [ ] **weight_bits**. What are the possible bit resolutions of weights? 
- [ ] **activation_bits**. What are the possible bit resolutions of activations? 
- [ ] **neurons**. How many neurons fit on one chip? If it depends on the neuron model, provide an example for the most common neuron model. This field can take a (short) sentence if need be.
- [ ] **synapses**. How many synapses for a given neuron config? This field can take a (short) sentence if need be.
- [ ] **on_chip_learning**. Does the chip support on chip learning?

Following info should be added in the text body. 
- [ ] What makes the chip stand out in neuromorphic computing?
- [ ] Practical applications of the chip
- [ ] What's the workflow to develop and deploy models for the chip? What are the software toolchains involved?
- [ ] Availability to purchase / access 
- [ ] Scalibility - Can I stack this chip easily?
- [ ] Form factors. Are there boards available that can go on small drones? Robots? Data centers?

Following things would be nice to have:
- [ ] Links to documents / data sheets that describe the chip.
- [ ] Technology and fabrication details.
- [ ] Future development roadmap.
- [ ] List of publications that show results on the hardware, including date, title, authors and journal/conference.

Feel free to add any relevant information you think would be beneficial. If you have questions or need clarification on any topic, please open a PR and ask. We encourage both seasoned contributors and newcomers to participate. Our team is ready to assist you in this process, both on Github or on Discord. Please keep the discussions public at all times.

## Workflow
1. Comment on this issue to express interest, so that our team can assign it to you. That'll let other people know that you're working on it.
2. Fork this repository 
3. Make the changes in your fork and commit them on a new branch.
4. Follow the [instructions](https://github.com/open-neuromorphic/open-neuromorphic.github.io?tab=readme-ov-file#-getting-started) to build the website locally and check that the new page renders nicely.
5. Create a pull request from the new branch in your fork into `main` in the original repository.

## Writing style 
Our aim is to create a central hub for educational content on neuromorphic computing. The content should be formally written, accessible to the public, and include references or images where appropriate. Feel free to include yourself in an authors statement at the bottom of the page. Please avoid overly general comments (as sometimes generated by ChatGPT).

**Comment by DRosen766** [comment]
I can complete this

**Comment by biphasic** [comment]
@DRosen766 I have updated the issue description to clarify the workflow and added a few more points on info that should go into the article. Any questions let me know

**Comment by DRosen766** [comment]
@biphasic Sounds good, working on it now

**Comment by DRosen766** [comment]
Still working on installing.  For someone who installed/built properly, did you need the extended version of hugo?

**Comment by DRosen766** [comment]
I'm receiving this error when running the dev script: 
`failed to process shortcode: "~\open-neuromorphic.github.io\themes\hugoplate\layouts\shortcodes\override-image.html:30:6": execute of template failed: template: shortcodes/override-image.html:30:6: executing "shortcodes/override-image.html" at <fileExists (add `static/` $imagePath)>: error calling fileExists: CreateFile ~\open-neuromorphic.github.io\static\https:\d3i71xaburhd42.cloudfront.net\df3434c56233f707da2383620667d57632eaff72\2-Figure1-1.png: The filename, directory name, or volume label syntax is incorrect.`

It seems some of the shortcodes are not compatible with Windows machines because of the format of paths (direction of /).  So things like fileExists are breaking.  I'm happy to work on fixing, @biphasic 
 want me to open a new issue?

**Comment by neural-loop** [comment]
Hi @DRosen766, please do correct the shortcodes for Windows if you are able. Odd that it still errors on WSL. I don't immediately recognize the cloudfront path.

**Comment by DRosen766** [comment]
@neural-loop The cloudfront path is the url of the image in index.md.  Would it be possible to just add those images to the repo so they are stored locally and don't have to be downloading the image every time.

**Comment by neural-loop** [comment]
@DRosen766 I added the images in a new commit, does that prevent the error?

**Comment by DRosen766** [comment]
@neural-loop Yeah, working now thanks

**Comment by cantordust** [comment]
@DRosen766 I'd be happy to contribute to this too, I recently had some close encounters with Akida.

**Comment by DRosen766** [comment]
@cantordust sounds good, want access to my fork or are you making your own?

**Comment by biphasic** [comment]
It's normally easiest if you add him as a collaborator in your fork (check settings in the fork repo)

**Comment by wbenoot** [comment]
The same goes for me, I can double check / review any of the more ambiguous parts If you guys like that. Recently had some very deep dives into the underlying implementation.

**Comment by DRosen766** [comment]
@wbenoot I'll add you as well.  I'm still very new to this stuff so that sounds great.

**Comment by neural-loop** [comment]
Just an idea, it might be easier to collaboratively write it up in a shared google doc and then move it over to markdown once everyone is happy with it.

**Comment by wbenoot** [comment]
I agree, especially if you still need to set up the website locally. We could also meet on Discord once to get cracking on all these checkboxes and the document.

**Comment by DRosen766** [comment]
@wbenoot sounds good
What time zone are you in?

**Comment by wbenoot** [comment]
I'm in CET, I'm free this weekend if you guys are up for it @DRosen766 @cantordust ?

**Comment by biphasic** [comment]
@wbenoot if you could take the lead on drafting a first version that would be fantastic. Then @DRosen766 and @cantordust can fill in info! Feel free to use Gdocs if you think it's easier. I'm happy to render it locally to test that everything looks good on the website if it helps. I'll be available on the weekend. Saturday early afternoon? Sunday evening?

**Comment by DRosen766** [comment]
@biphasic Sounds good. Sunday works for me.

**Comment by wbenoot** [comment]
I can also join for a moment sunday evening

**Comment by DRosen766** [comment]
I have all the first section except synapses

**Comment by DRosen766** [comment]
pushed intro data to my repo

**Comment by biphasic** [comment]
great! Do you think you could open a pull request from your feature branch in your fork into the main branch of this repo? You can mark it as draft, but that would make it visible to everyone

**Comment by cantordust** [comment]
@DRosen766 Apologies, I had misconfigured my GitHub notifications🤦. If the offer is still on the table, I can work in your branch, otherwise I can make my own fork.

**Comment by DRosen766** [comment]
@cantordust no problem.  You should have an invite from my fork from a couple weeks ago.  You're welcome to join that

**Comment by cantordust** [comment]
Ah shoot, it has expired :( Would you be able to send another one please?🙏

**Comment by DRosen766** [comment]
@cantordust for sure, just sent

**Comment by cantordust** [comment]
Thank you, accepted! 👍🏼

**Comment by biphasic** [comment]
Hey peeps, @cantordust @wbenoot could you please add some more info to @DRosen766 's branch? https://github.com/open-neuromorphic/open-neuromorphic.github.io/pull/173 Thanks a lot

**Comment by cantordust** [comment]
@biphasic I finally had some time to sit down and focus on this. I added information about the parts that I have had experience with, mainly training. Other parts can probably be extended further. Let me know if anything needs to be changed!

**Comment by biphasic** [comment]
Where can I see those changes? Because they're not in the open PR, that means you didn't push them on his branch

**Comment by biphasic** [comment]
closed in https://github.com/open-neuromorphic/open-neuromorphic.github.io/pull/173
