### ISSUE TITLE
Add Google calendar to render directly on website, or at least add link to it

### ISSUE THREAD

**Issue by biphasic** [open-neuromorphic/open-neuromorphic.github.io#23]

**Comment by neural-loop** [comment]
![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/654993/e06cf7d1-efbf-49c3-a786-39a4358c9a52)

Maybe can make a modal popup around the events somewhere with a "View Google Calendar" link, if the purpose is to make it easy for people to set a reminder.

**Comment by neural-loop** [comment]
I looked at adding it as a modal, but it seems to load slowly as its an external widget (note the turtles on the network tab), this is the main issue I'd see with having it on the front page.

![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/654993/e8f306f2-6d15-49e7-8204-8c3c817ad505)

What is the goal for the google calendar? We could have a /calendar/ page that opens to the calendar. 

If the idea is to be a place to (easily) announce events without web interaction, it might not be ideal - wouldn't provide a sharable link that could go out to LinkedIn, Twitter and the like.

If it is meant to be a way for people to track an upcoming event, maybe we could add calendar links to the individual events https://help.lafayette.edu/generate-a-url-to-add-events-to-google-calendar/

**Comment by biphasic** [comment]
Thanks so much for looking into this. My idea was that people can add the calendar to whatever calendar app they're using. That would make the events show up immediately in their calendars. One reason I looked into this originally was also the difficulty to distribute the zoom link ahead of time, because we were only able to generate them a few days in advance. The Google calendar event could be updated easily. But actually our strategy changed now to streaming live on YouTube and always direct people onto the same channel landing page where the live stream will be listed. Plus Fabrizio now also sends out newsletters ahead of time via email. So the calendar is not crucial. To be honest I haven't seen in use anywhere else
