### ISSUE TITLE
Some SEO suggestions

### ISSUE THREAD

**Issue by neural-loop** [open-neuromorphic/open-neuromorphic.github.io#27]
- [ ] Verify Domain in github and add to various repositories -> https://open-neuromorphic.org/
- [x] Link to socials at https://github.com/open-neuromorphic
	https://open-neuromorphic.org/
	https://discord.gg/C9bzWgNmqk
	https://www.linkedin.com/groups/9267873
	https://www.youtube.com/@openneuromorphic
- [x] Optimize title & description at https://open-neuromorphic.org/
        (Suggestion) Discover the Future of Computing with Open Neuromorphic: Your Hub for Open-Source Projects in Neuromorphic Research
- [x] Include '- Open Neuromorphic' in page titles example: https://open-neuromorphic.org/p/snn-library-benchmarks/

Strategy wise, I would recommend targeting some keywords, 'neuromorphic computing', 'neuromorphic ai'. A good way to do this is through data architecture, possibly via the tagging mechanism. 

- Data structure like https://open-neuromorphic.org/neuromorphic-computing/articles faqs etc
- Left column of site navigation should feature links that lead to these content sections.

I am open to help & collaboration! These are some small steps that can help keep things trending in the right direction. There is a ton more that is possible. 

I added Open Neuromorphic to https://aimodels.org/ai-community-directory . I've recently started an article on Neuromorphic computing: https://aimodels.org/neuromorphic-computing and developing this page and subject further is what brought me here. :)

**Comment by biphasic** [comment]
super nice, thanks for that! Would you mind opening some pull requests for that? Would definitely help to get better exposure

**Comment by neural-loop** [comment]
@biphasic Good suggestion - I've spent the last week studying Hugo and migrating an existing site to use it. I should be able to get some pull requests up once I finish the migration.

**Comment by biphasic** [comment]
For the first point, the domain is verified for the ONM organization profile, but it says 'DNS check in progress' in the settings for the open-neuromorphic.github.io repo. Should I change this?

**Comment by neural-loop** [comment]
This is to look more at https://github.com/organizations/open-neuromorphic/settings/profile

This will have a number of fields (my github as example):
![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/654993/fb6c778e-8d10-4b00-93f3-b407cb5fdfac)

This is a likely landing page (second result for Open Neuromorphic), so it would be good to have at least Discord and Website on the org landing page.

![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/654993/230e215f-388e-46f0-9cf7-5479e6135b40)

**Comment by biphasic** [comment]
done!

**Comment by neural-loop** [comment]
It doesn't show verified, though it's probably not *that* important. It's something I thought could potentially be a signal somewhere, but it's just a wild guess on my part. We can mark this complete! Looks good!

**Comment by neural-loop** [comment]
anoyher fyi: You might want to look into 
![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/654993/6f143da6-0591-4151-b9f8-a553fbdc6f8e)
And see if you can get neuromorphic * topics in there too. Again, it's probably not that important, but could be a signal somewhere.
