### ISSUE TITLE
Building Neuromorphic Hardware Directory

### ISSUE THREAD

**Issue by biphasic** [open-neuromorphic/open-neuromorphic.github.io#70]
Ideally this is rendered directly from our github repository, so that people can open pull requests to update info. I'm including a nice summary table about hardware from http://sandamirskaya.eu/resources/SandamirskayaEtAl2022_SciRob.pdf

![image](https://github.com/open-neuromorphic/open-neuromorphic.github.io/assets/11279568/62292d6b-d9f1-4a60-a423-ff6e82cfe466)

**Comment by neural-loop** [comment]
I copied the table and asked gpt to turn it into a markdown list with checkboxes, that we can use this as a working place. 

As is, we could add a neuromorphic-hardware page that contains these as a table. Along the idea of having something where people can add pull requests, we'd probably want to have individual pages with more information. 

Some additional information we could add to these that would start to produce enough unique information for individual pages. It's not necessary to fill all of these things, but if we had a few that were fully fleshed out, it could be a good example to point to when asking for submissions

- Image / or images
- Separate company name from chip name
- Link to company / organization (maybe socials?) 
- Link to product page
- Description / the 'story' of the architecture or practical use examples
- Software (are there links, github addresses?)
- Applications  (similar to software)


- [ ] **ROLLS (16)**
  - Chip type: Mixed-signal
  - #Neurons/synapses: 256/64 K
  - On-chip learning: Y
  - Power: ~5 mW
  - Software: Custom python
  - Applications: Research

- [ ] **DYNAP-SE (15)**
  - Chip type: Mixed-signal
  - #Neurons/synapses: 4 K/4 M
  - On-chip learning: N
  - Power: ~5 mW
  - Software: Custom python
  - Applications: Research

- [ ] **NeuroGrid (BrainDrop)/Stanford (29)**
  - Chip type: Mixed-signal
  - #Neurons/synapses: 1 M/billions
  - On-chip learning: N
  - Power: ~3 W
  - Software: NEF
  - Applications: Real-time SNN emulation

- [ ] **Innatera**
  - Chip type: Mixed-signal
  - #Neurons/synapses: 256/64 K
  - On-chip learning: N
  - Power: ~1 mW
  - Software: PyTorch
  - Applications: Smart sensing

- [ ] **BrainScaleS 1/Universität Heidelberg (17)**
  - Chip type: Mixed-signal
  - #Neurons/synapses: ~180,000/40 M (in 352 chips)
  - On-chip learning: N
  - Power: ~300 W
  - Software: BrainScaleS OS
  - Applications: Accelerated SNN emulation; HPC

- [ ] **BrainScaleS 2/Universität Heidelberg (30, 31)**
  - Chip type: Mixed-signal
  - #Neurons/synapses: 512/~130,000
  - On-chip learning: Y
  - Power: ~1 W
  - Software: BrainScaleS OS
  - Applications: Edge processing, robotics

- [ ] **TrueNorth/IBM (9)**
  - Chip type: Digital
  - #Neurons/synapses: 1 M/256 M (in 4 K cores)
  - On-chip learning: N
  - Power: ~0.3 W
  - Software: Custom
  - Applications: DNN acceleration

- [ ] **SpiNNaker/University of Manchester (13)**
  - Chip type: Digital
  - #Neurons/synapses: 1B/10 kilobytes (in 64 K x 18 ARM cores)
  - On-chip learning: Y
  - Power: ~kW
  - Software: PyNN, NEST
  - Applications: Real-time simulation of SNN; HPC

- [ ] **Loihi/Intel Labs (12)**
  - Chip type: Digital
  - #Neurons/synapses: ~128,000/128 M per chip (scalable)
  - On-chip learning: Y
  - Power: ~1 W
  - Software: Lava Research chip

- [ ] **Dynap-CNN/SynSense**
  - Chip type: Digital
  - #Neurons/synapses: ~327,000/278,000
  - On-chip learning: N
  - Power: ~5 mW
  - Software: Rockpool, PyTorch
  - Applications: Smart sensing

- [ ] **BrainChip/Akida**
  - Chip type: Digital
  - #Neurons/synapses: Configurable, 8-Mb SRAM
  - On-chip learning: Y
  - Power: ~30 mW
  - Software: TensorFlow, CNN → SNN
  - Applications: Smart sensing, one-shot learning

- [ ] **Tianjic/Tsinghua University (34)**
  - Chip type: Digital
  - #Neurons/synapses: 40,000/10 M (on 156 cores)
  - On-chip learning: N
  - Power: ~1 W
  - Software: Custom
  - Applications: ANN/SNN acceleration

**Comment by neural-loop** [comment]
Getting a template going

# [Chipname]

## 1. Basic Information
   - **Chipname:** [Provide chip name]
   - **Company/Lab:** [Provide company/lab name]
   - **Chip Type:** [Digital/Mixed-signal]
   - **# Neurons/Synapses:** [Specify numbers]
   - **On-Chip Learning:** [Yes/No]
   - **Power:** [Specify power consumption]
   - **Software:** [Specify software tools used]
   - **Applications:** [Specify applications]

## 2. Additional Information
   - **Image/Images:** [Insert image links]
   - **Company/Organization:**
      - **Profile of Team or Group:** [Provide details]
      - **Profile of Organization or Company:** [Provide details]
      - **Social Media Links:**
         - LinkedIn: [Provide link]
         - Twitter: [Provide link]
         - Wikipedia: [Provide link]
      - **Product Page Link:** [Provide link]
      - **Company Logo:** [Insert logo image link]
      - **Website:** [Provide link]

## 3. Body
   - **Product Description:** [Provide a detailed product description]
   - **Story of Architecture:** [Explain the architecture or share the design story]
   - **Benchmark Results:** [Include benchmark results if available]
   - **Practical Use Examples:** [Provide real-world applications and examples]

## 4. Team/Company Description
   - [Provide a detailed description of the team or company behind the chip]

## Example Template for Researchers
```markdown
# [Chipname]

## 1. Basic Information
   - **Chipname:** [Provide chip name]
   - **Company/Lab:** [Provide company/lab name]
   - **Chip Type:** [Digital/Mixed-signal]
   - **# Neurons/Synapses:** [Specify numbers]
   - **On-Chip Learning:** [Yes/No]
   - **Power:** [Specify power consumption]
   - **Software:** [Specify software tools used]
   - **Applications:** [Specify applications]

## 2. Additional Information
   - **Image/Images:** [Insert image links]
   - **Company/Organization:**
      - **Profile of Team or Group:** [Provide details]
      - **Profile of Organization or Company:** [Provide details]
      - **Social Media Links:**
         - LinkedIn: [Provide link]
         - Twitter: [Provide link]
         - Wikipedia: [Provide link]
      - **Product Page Link:** [Provide link]
      - **Company Logo:** [Insert logo image link]
      - **Website:** [Provide link]

## 3. Body
   - **Product Description:** [Provide a detailed product description]
   - **Story of Architecture:** [Explain the architecture or share the design story]
   - **Benchmark Results:** [Include benchmark results if available]
   - **Practical Use Examples:** [Provide real-world applications and examples]

## 4. Team/Company Description
   - [Provide a detailed description of the team or company behind the chip]
