### ISSUE TITLE
Display total number of people on Discord on the homepage 

### ISSUE THREAD

**Issue by biphasic** [open-neuromorphic/open-neuromorphic.github.io#99]
It would be great to showcase the fact that we're several hundred people already. This would ideally show up somewhere on the front page of open-neuromorphic.org. 
Ideally that number is fetched dynamically, but if that's not possible, a '700+' text would also do for the moment.

**Comment by neural-loop** [comment]
@biphasic  Dynamic would be a bit involved, from what I can see would be setting up some bot / application and dealing with tokens and secrets. I put 790 joined, can put that to 790+ or something else. Please review and if it is good we can close this and just remember to update it occasionally

**Comment by biphasic** [comment]
me likes! Thank you!
